### ISSUE TITLE
OSError: [Errno 98] Address in use

### ISSUE THREAD

**Issue by aminfekri** [mosajjal/byosh#10]
why?
<img width="515" alt="Screen Shot 1400-10-22 at 17 10 48" src="https://user-images.githubusercontent.com/45711115/149151374-cbc66a05-fa1d-48a6-81b3-1f5e70830c17.png">

**Comment by mosajjal** [comment]
looks like port 53 is used by another process. you can use this to see which process is using it:
```
sudo ss -nap | grep :53 |grep udp
``` 
If you're using a `systemd`-based Distro, odds are `systemd-resolved` is the one listening on that port and interfering with `byosh`
